
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nicolas
 */
public class nervioso extends javax.swing.JFrame {

    /**
     * Creates new form nervioso
     */
    public nervioso() {
        initComponents();
        methods.scaleImage1(superficial, "src/imagenes/SistemaNervioso.jpg");
        methods.scaleImage1(superficialE, "src/imagenes/SistemaNerviosoE.jpg");
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Superficial");
    nervioso_01 objeto5=new nervioso_01("SISTEMA NERVIOSO DEL CUERPO HUMANOS",21,
            "El sistema nervioso es el encargado de conectar"
             +"\nel mundo exterior con el interior mediante estímulos"
             + "\ny reacciones físicas o químicas. Los nervios son un "
             + "\nconjunto de fibras que conducen los impulsos que se "
             + "\nreciben en el sistema nervioso central y "
             + "\nque se distribuyen por diferentes partes de cuerpo "
             + "\nmediante ondas eléctricas que circulan a una "
             + "\ngran velocidad",
            "Basicamente el sistema nervioso nos permite"
             +"\nsentir los diferentes estimulos que "
             + "\nnuestro cuerpo pueda sufrír","Todo el cuerpo");
        
        text5.setText("\n\nNombre del sistema:" +objeto5.getNombres()
                +"\n\nCantidad de partes: "
                +objeto5.getCantidad_partes()+"\n\nInformación del sistema: "
                +objeto5.getInformacion()+"\n\nFunciones del sistema: "
                +objeto5.getFunciones()+"\n\nUbicación de los nervios: "
                +objeto5.getUbicaion());
       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        volver = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        superficial = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text5 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        validar = new javax.swing.JButton();
        superficialE = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt1 = new javax.swing.JComboBox<>();
        txt2 = new javax.swing.JComboBox<>();
        txt3 = new javax.swing.JComboBox<>();
        txt4 = new javax.swing.JComboBox<>();
        txt5 = new javax.swing.JComboBox<>();
        txt6 = new javax.swing.JComboBox<>();
        txt7 = new javax.swing.JComboBox<>();
        txt8 = new javax.swing.JComboBox<>();
        txt9 = new javax.swing.JComboBox<>();
        txt10 = new javax.swing.JComboBox<>();
        txt11 = new javax.swing.JComboBox<>();
        txt12 = new javax.swing.JComboBox<>();
        txt13 = new javax.swing.JComboBox<>();
        txt14 = new javax.swing.JComboBox<>();
        txt15 = new javax.swing.JComboBox<>();
        txt16 = new javax.swing.JComboBox<>();
        txt17 = new javax.swing.JComboBox<>();
        txt18 = new javax.swing.JComboBox<>();
        txt19 = new javax.swing.JComboBox<>();
        txt20 = new javax.swing.JComboBox<>();
        txt21 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setAutoscrolls(true);

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        jTabbedPane2.setToolTipText("");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        superficial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        text5.setEditable(false);
        text5.setColumns(20);
        text5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        text5.setRows(5);
        text5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(text5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(superficial, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(superficial, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Partes", jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        validar.setText("Validar");
        validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarActionPerformed(evt);
            }
        });

        superficialE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("1.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("2.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("3.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("4.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("5.");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("10.");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("6.");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("7.");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("8.");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("9.");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("15.");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("11.");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("12.");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("13.");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("14.");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("16.");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("17.");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("18.");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("19.");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("20.");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("21.");

        txt1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeno", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama platar lateral", "Rama platar medial", "Nervio sural" }));

        txt2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeno", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama platar lateral", "Rama platar medial", "Nervio sural" }));

        txt3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeno", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama platar lateral", "Rama platar medial", "Nervio sural" }));

        txt4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeno", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama platar lateral", "Rama platar medial", "Nervio sural" }));

        txt5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeno", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama platar lateral", "Rama platar medial", "Nervio sural" }));

        txt6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeno", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama platar lateral", "Rama platar medial", "Nervio sural" }));
        txt6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txt7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeno", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama platar lateral", "Rama platar medial", "Nervio sural" }));

        txt8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeno", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama platar lateral", "Rama platar medial", "Nervio sural" }));

        txt9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeno", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama platar lateral", "Rama platar medial", "Nervio sural" }));

        txt10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeno", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama platar lateral", "Rama platar medial", "Nervio sural" }));

        txt11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeno", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama platar lateral", "Rama platar medial", "Nervio sural" }));

        txt12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeno", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama platar lateral", "Rama platar medial", "Nervio sural" }));

        txt13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeno", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama platar lateral", "Rama platar medial", "Nervio sural" }));

        txt14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeno", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama platar lateral", "Rama platar medial", "Nervio sural" }));

        txt15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeo", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama plantar lateral", "Rama plantar medial", "Nervio sural" }));

        txt16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeno", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama platar lateral", "Rama platar medial", "Nervio sural" }));

        txt17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeno", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama platar lateral", "Rama platar medial", "Nervio sural" }));

        txt18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeno", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama platar lateral", "Rama platar medial", "Nervio sural" }));

        txt19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeno", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama platar lateral", "Rama platar medial", "Nervio sural" }));

        txt20.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeno", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama plantar lateral", "Rama plantar medial", "Nervio sural" }));
        txt20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txt21.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Cerebro", "Cerebelo", "Bulbo raquídeo", "Plexo cervical", "Plexo braquial", "Nervio frénico", "Nervios torácicos", "Nervio radial", "Plexo sacro-croxígeo", "Plexo lumbar", "Nervio cubital", "Nervio ciático", "Nervio saferno", "Nervio femoro-cutáneo", "Nervio peroneo común", "Nervio cutáneo medial", "Nervio cutáneo lateral", "Nervio tibial", "Rama plantar lateral", "Rama plantar medial", "Nervio sural" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(superficialE, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel12)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt9, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                    .addComponent(txt8, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                    .addComponent(txt7, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                    .addComponent(txt6, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt21, 0, 232, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel21)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt19, javax.swing.GroupLayout.Alignment.LEADING, 0, 232, Short.MAX_VALUE)
                                    .addComponent(txt18, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt17, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt20, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt16, 0, 162, Short.MAX_VALUE)
                            .addComponent(txt10, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt11, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt12, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt13, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt14, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt15, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                        .addComponent(validar)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel19)
                            .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel20)
                            .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel21)
                            .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel22)
                            .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel23)
                            .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txt13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txt14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(validar)
                            .addComponent(txt16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(superficialE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Practica", jPanel7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(volver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volver)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistema nervioso del cuerpo humano");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        humano uno = new humano();
        uno.setVisible(true);
        dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void validarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarActionPerformed
        // TODO add your handling code here:
        int[] ans = new int[3];
        ans[0] = 0;
        ans[1] = 0;
        ans[2] = 0;

        methods.validar(txt1, "Cerebelo", ans);
        methods.validar(txt2, "Plexo cervical", ans);
        methods.validar(txt3, "Nervio frénico", ans);
        methods.validar(txt4, "Nervio radial", ans);
        methods.validar(txt5, "Plexo lumbar", ans);
        methods.validar(txt6, "Nervio cubital", ans);
        methods.validar(txt7, "Nervio ciático", ans);
        methods.validar(txt8, "Nervio peroneo común", ans);
        methods.validar(txt9, "Nervio cutáneo lateral", ans);
        methods.validar(txt10, "Nervio sural", ans);
        methods.validar(txt11, "Cerebro", ans);
        methods.validar(txt12, "Bulbo raquídeo", ans);
        methods.validar(txt13, "Plexo braquial", ans);
        methods.validar(txt14, "Nervios torácicos", ans);
        methods.validar(txt15, "Plexo sacro-croxígeo", ans);
        methods.validar(txt16, "Nervio saferno", ans);
        methods.validar(txt17, "Nervio femoro-cutáneo", ans);
        methods.validar(txt18, "Nervio cutáneo medial", ans);
        methods.validar(txt19, "Nervio tibial", ans);
        methods.validar(txt20, "Rama plantar lateral", ans);
        methods.validar(txt21, "Rama plantar medial", ans);

        if (ans[0] <= 6) {
            JOptionPane.showMessageDialog(null, "Aciertos: " + ans[0] + "\nFallos:" + ans[2] + "\nSin responder:" + ans[1], "Desempeño bajo", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/imagenes/bad.gif"));
        } else if (ans[0] > 6 && ans[0] < 11) {
            JOptionPane.showMessageDialog(null, "Aciertos: " + ans[0] + "\nFallos:" + ans[2] + "\nSin responder:" + ans[1], "Desempeño medio", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/imagenes/maomeno.gif"));
        } else if (ans[0] >= 11 && ans[0] < 21) {
            JOptionPane.showMessageDialog(null, "Aciertos: " + ans[0] + "\nFallos:" + ans[2] + "\nSin responder:" + ans[1], "Desempeño superior", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/imagenes/good.gif"));
        } else if (ans[0] == 21) {
            JOptionPane.showMessageDialog(null, "Aciertos: " + ans[0] + "\nFallos:" + ans[2] + "\nSin responder:" + ans[1], "Desempeño perfecto", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/imagenes/perfect.gif"));
        }
    }//GEN-LAST:event_validarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nervioso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nervioso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nervioso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nervioso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nervioso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel superficial;
    private javax.swing.JLabel superficialE;
    private javax.swing.JTextArea text5;
    private javax.swing.JComboBox<String> txt1;
    private javax.swing.JComboBox<String> txt10;
    private javax.swing.JComboBox<String> txt11;
    private javax.swing.JComboBox<String> txt12;
    private javax.swing.JComboBox<String> txt13;
    private javax.swing.JComboBox<String> txt14;
    private javax.swing.JComboBox<String> txt15;
    private javax.swing.JComboBox<String> txt16;
    private javax.swing.JComboBox<String> txt17;
    private javax.swing.JComboBox<String> txt18;
    private javax.swing.JComboBox<String> txt19;
    private javax.swing.JComboBox<String> txt2;
    private javax.swing.JComboBox<String> txt20;
    private javax.swing.JComboBox<String> txt21;
    private javax.swing.JComboBox<String> txt3;
    private javax.swing.JComboBox<String> txt4;
    private javax.swing.JComboBox<String> txt5;
    private javax.swing.JComboBox<String> txt6;
    private javax.swing.JComboBox<String> txt7;
    private javax.swing.JComboBox<String> txt8;
    private javax.swing.JComboBox<String> txt9;
    private javax.swing.JButton validar;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
