
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Nicolas
 */
public class oseo extends javax.swing.JFrame {

    /**
     * Creates new form oseo
     */
    public oseo() {
        initComponents();
        methods.scaleImage1(superficial, "src/imagenes/SistemaOseo.jpg");
        methods.scaleImage1(superficialE, "src/imagenes/SistemaOseoE.jpg");
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Superficial");
        oseo_01 objeto4=new oseo_01("SISTEMA OSEO DEL CUERPO HUMANO",35,
               "El hueso es el órgano más resistente, duro y fuerte que se puede"
               + "\nencontrar en el cuerpo de los vertebrados. "
               + "\nLos huesos se conforman por diversos tejidos duros y blandos,"
               + "\nel principal tejido duro es el tejido óseo. "
               + "\nLos huesos poseen una cubierta superficial llamada periostio "
               + "\ny están formados por un tejido conectivo fibroso, "
               + "\nmientras que la superficie articular está cubierta por el tejido"
               + " \ncartilaginoso. Los huesos son muy livianos pero a su vez"
               + " \nresistentes y muy duros."
               ,"Basicamente los huesos son los pilares con los cuales"
               + "\nel cuerpo se sostiene para moverse"
                  , " 933 kg/m3","Todo el cuerpo",14.4); 
        text4.setText("\n\nNombre del sistema:" +objeto4.getNombres()
                +"\n\nCantidad de partes: "
                +objeto4.getCantidad_partes()+"\n\nInformación del sistema: "
                +objeto4.getInformacion()+"\n\nFunciones del sistema: "
                +objeto4.getFunciones()+"\n\nTamaño promedio de los huesos y densidad: "
                +objeto4.getVolumen()+"\n\nUbicación principal de los músculos:"
                +objeto4.getUbicaion()+"\n\nLongitud promedio de los huesos: "
                +objeto4.getLargo()+"Pulgadas");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        volver = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        superficial = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text4 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        validar = new javax.swing.JButton();
        superficialE = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txt1 = new javax.swing.JComboBox<>();
        txt2 = new javax.swing.JComboBox<>();
        txt3 = new javax.swing.JComboBox<>();
        txt4 = new javax.swing.JComboBox<>();
        txt5 = new javax.swing.JComboBox<>();
        txt6 = new javax.swing.JComboBox<>();
        txt7 = new javax.swing.JComboBox<>();
        txt8 = new javax.swing.JComboBox<>();
        txt9 = new javax.swing.JComboBox<>();
        txt10 = new javax.swing.JComboBox<>();
        txt11 = new javax.swing.JComboBox<>();
        txt12 = new javax.swing.JComboBox<>();
        txt13 = new javax.swing.JComboBox<>();
        txt14 = new javax.swing.JComboBox<>();
        txt15 = new javax.swing.JComboBox<>();
        txt16 = new javax.swing.JComboBox<>();
        txt17 = new javax.swing.JComboBox<>();
        txt18 = new javax.swing.JComboBox<>();
        txt19 = new javax.swing.JComboBox<>();
        txt20 = new javax.swing.JComboBox<>();
        txt21 = new javax.swing.JComboBox<>();
        txt22 = new javax.swing.JComboBox<>();
        txt23 = new javax.swing.JComboBox<>();
        txt24 = new javax.swing.JComboBox<>();
        txt25 = new javax.swing.JComboBox<>();
        txt26 = new javax.swing.JComboBox<>();
        txt27 = new javax.swing.JComboBox<>();
        txt28 = new javax.swing.JComboBox<>();
        txt29 = new javax.swing.JComboBox<>();
        txt30 = new javax.swing.JComboBox<>();
        txt31 = new javax.swing.JComboBox<>();
        txt32 = new javax.swing.JComboBox<>();
        txt33 = new javax.swing.JComboBox<>();
        txt34 = new javax.swing.JComboBox<>();
        txt35 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setAutoscrolls(true);

        volver.setText("Volver ");
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        jTabbedPane2.setToolTipText("");
        jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        superficial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        text4.setEditable(false);
        text4.setColumns(20);
        text4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        text4.setRows(5);
        text4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(text4);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(superficial, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(superficial, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Partes", jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        validar.setText("Validar");
        validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarActionPerformed(evt);
            }
        });

        superficialE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("1.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("2.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("3.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("4.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("5.");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("10.");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("6.");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("7.");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("8.");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("9.");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("15.");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("11.");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("12.");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("13.");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("14.");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("16.");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("17.");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("18.");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("19.");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("20.");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("21.");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("22.");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("23.");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("24.");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("25.");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("26.");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("27.");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("28.");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("29.");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("30.");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("31.");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("32.");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("33.");

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("34.");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("35.");

        txt1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));

        txt2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));

        txt3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));

        txt4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));

        txt5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));

        txt6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));

        txt7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));

        txt8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));

        txt9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));

        txt10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));

        txt11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));

        txt12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));

        txt13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));

        txt14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));

        txt15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));

        txt16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));

        txt17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));
        txt17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt17ActionPerformed(evt);
            }
        });

        txt18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));
        txt18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt18ActionPerformed(evt);
            }
        });

        txt19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));
        txt19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt19ActionPerformed(evt);
            }
        });

        txt20.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));
        txt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt20ActionPerformed(evt);
            }
        });

        txt21.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));
        txt21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt21ActionPerformed(evt);
            }
        });

        txt22.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));
        txt22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt22ActionPerformed(evt);
            }
        });

        txt23.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));
        txt23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt23ActionPerformed(evt);
            }
        });

        txt24.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));
        txt24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt24ActionPerformed(evt);
            }
        });

        txt25.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));
        txt25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt25ActionPerformed(evt);
            }
        });

        txt26.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));
        txt26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt26ActionPerformed(evt);
            }
        });

        txt27.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));
        txt27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt27ActionPerformed(evt);
            }
        });

        txt28.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));
        txt28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt28ActionPerformed(evt);
            }
        });

        txt29.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));
        txt29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt29ActionPerformed(evt);
            }
        });

        txt30.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));
        txt30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt30ActionPerformed(evt);
            }
        });

        txt31.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));
        txt31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt31ActionPerformed(evt);
            }
        });

        txt32.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));
        txt32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt32ActionPerformed(evt);
            }
        });

        txt33.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));
        txt33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt33ActionPerformed(evt);
            }
        });

        txt34.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));
        txt34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt34ActionPerformed(evt);
            }
        });

        txt35.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Párietal", "Maxilar", "Vertebras Cervicales", "Clavícula", "Escápula", "Húmero", "Costillas", "Radio", "Iliaco", "Cúbito", "Cuello del Femur", "Fémur", "Condilo Interno", "Condilo Externo", "Tibia", "Perone", "Hueso Frontal", "Tabique Nasal", "Mandíbula", "Cabeza del Humero", "Manubrio del Esternón", "Cuerpo del Esternón", "Vertebra Toracica", "Costilla", "Cresta Ilíaca", "Hueso Sacro", "Coxis", "Cabeza del Femur", "Carpo", "Rótula", "Condilo Lateral", "Cabeza de Peroné", "Maleolo Interno", "Maleolo Externo", "Cuneiforme" }));
        txt35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt35ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(superficialE, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel12)
                    .addComponent(jLabel18))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt13, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt14, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt15, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt16, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt17, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt18, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt19, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt34, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt33, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt35, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt21, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt23, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt24, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt25, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt26, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt27, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt28, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt29, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt30, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt31, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txt32, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(validar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel19)
                            .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35)
                            .addComponent(txt33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel20)
                            .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36)
                            .addComponent(txt18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel21)
                            .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37)
                            .addComponent(txt19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel22)
                            .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel23)
                            .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel24)
                            .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25)
                                .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel26)
                            .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel27)
                            .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel28)
                            .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel29)
                            .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel30)
                            .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel31)
                            .addComponent(txt13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel32)
                            .addComponent(txt14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel33)
                            .addComponent(txt15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel34)
                            .addComponent(txt16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(validar)))
                    .addComponent(superficialE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Practica", jPanel7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(volver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volver)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistema óseo del cuerpo humano");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        humano uno = new humano();
        uno.setVisible(true);
        dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void validarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarActionPerformed
        // TODO add your handling code here:
        int[] ans = new int[3];
        ans[0] = 0;
        ans[1] = 0;
        ans[2] = 0;

        methods.validar(txt1, "Hueso frontal", ans);
        methods.validar(txt2, "Tabique nasal", ans);
        methods.validar(txt3, "Mandíbula", ans);
        methods.validar(txt4, "Cabeza del humero", ans);
        methods.validar(txt5, "Manubrio del esternón", ans);
        methods.validar(txt6, "Cuerpo del esternón", ans);
        methods.validar(txt7, "Vertebra toracica", ans);
        methods.validar(txt8, "Costilla", ans);
        methods.validar(txt9, "Cresta ilíaca", ans);
        methods.validar(txt10, "Hueso sacro", ans);
        methods.validar(txt11, "Coxis", ans);
        methods.validar(txt12, "Cabeza del Femur", ans);
        methods.validar(txt13, "Carpo", ans);
        methods.validar(txt14, "Rótula", ans);
        methods.validar(txt15, "Condilo lateral", ans);
        methods.validar(txt16, "Cabeza de peroné", ans);
        methods.validar(txt17, "Maleolo interno", ans);
        methods.validar(txt18, "Maleolo externo", ans);
        methods.validar(txt19, "Cuneiforme", ans);
        methods.validar(txt20, "Párietal", ans);
        methods.validar(txt21, "Maxilar", ans);
        methods.validar(txt22, "Vertebras cervicales", ans);
        methods.validar(txt23, "Clavícula", ans);
        methods.validar(txt24, "Escápula", ans);
        methods.validar(txt25, "Húmero", ans);
        methods.validar(txt26, "Costillas", ans);
        methods.validar(txt27, "Radio", ans);
        methods.validar(txt28, "Iliaco", ans);
        methods.validar(txt29, "Cúbito", ans);
        methods.validar(txt30, "Cuello del femur", ans);
        methods.validar(txt31, "Fémur", ans);
        methods.validar(txt32, "Condilo interno", ans);
        methods.validar(txt33, "Condilo externo", ans);
        methods.validar(txt34, "Tibia", ans);
        methods.validar(txt35, "Perone", ans);

        if (ans[0] <= 6) {
            JOptionPane.showMessageDialog(null, "Aciertos: " + ans[0] + "\nFallos:" + ans[2] + "\nSin responder:" + ans[1], "Desempeño bajo", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/imagenes/bad.gif"));
        } else if (ans[0] > 9 && ans[0] < 18) {
            JOptionPane.showMessageDialog(null, "Aciertos: " + ans[0] + "\nFallos:" + ans[2] + "\nSin responder:" + ans[1], "Desempeño medio", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/imagenes/maomeno.gif"));
        } else if (ans[0] >= 18 && ans[0] < 35) {
            JOptionPane.showMessageDialog(null, "Aciertos: " + ans[0] + "\nFallos:" + ans[2] + "\nSin responder:" + ans[1], "Desempeño superior", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/imagenes/good.gif"));
        } else if (ans[0] == 35) {
            JOptionPane.showMessageDialog(null, "Aciertos: " + ans[0] + "\nFallos:" + ans[2] + "\nSin responder:" + ans[1], "Desempeño perfecto", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/imagenes/perfect.gif"));
        }
    }//GEN-LAST:event_validarActionPerformed

    private void txt17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt17ActionPerformed

    private void txt18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt18ActionPerformed

    private void txt19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt19ActionPerformed

    private void txt20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt20ActionPerformed

    private void txt21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt21ActionPerformed

    private void txt22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt22ActionPerformed

    private void txt23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt23ActionPerformed

    private void txt24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt24ActionPerformed

    private void txt25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt25ActionPerformed

    private void txt26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt26ActionPerformed

    private void txt27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt27ActionPerformed

    private void txt28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt28ActionPerformed

    private void txt29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt29ActionPerformed

    private void txt30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt30ActionPerformed

    private void txt31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt31ActionPerformed

    private void txt32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt32ActionPerformed

    private void txt33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt33ActionPerformed

    private void txt34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt34ActionPerformed

    private void txt35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt35ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oseo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oseo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oseo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oseo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oseo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel superficial;
    private javax.swing.JLabel superficialE;
    private javax.swing.JTextArea text4;
    private javax.swing.JComboBox<String> txt1;
    private javax.swing.JComboBox<String> txt10;
    private javax.swing.JComboBox<String> txt11;
    private javax.swing.JComboBox<String> txt12;
    private javax.swing.JComboBox<String> txt13;
    private javax.swing.JComboBox<String> txt14;
    private javax.swing.JComboBox<String> txt15;
    private javax.swing.JComboBox<String> txt16;
    private javax.swing.JComboBox<String> txt17;
    private javax.swing.JComboBox<String> txt18;
    private javax.swing.JComboBox<String> txt19;
    private javax.swing.JComboBox<String> txt2;
    private javax.swing.JComboBox<String> txt20;
    private javax.swing.JComboBox<String> txt21;
    private javax.swing.JComboBox<String> txt22;
    private javax.swing.JComboBox<String> txt23;
    private javax.swing.JComboBox<String> txt24;
    private javax.swing.JComboBox<String> txt25;
    private javax.swing.JComboBox<String> txt26;
    private javax.swing.JComboBox<String> txt27;
    private javax.swing.JComboBox<String> txt28;
    private javax.swing.JComboBox<String> txt29;
    private javax.swing.JComboBox<String> txt3;
    private javax.swing.JComboBox<String> txt30;
    private javax.swing.JComboBox<String> txt31;
    private javax.swing.JComboBox<String> txt32;
    private javax.swing.JComboBox<String> txt33;
    private javax.swing.JComboBox<String> txt34;
    private javax.swing.JComboBox<String> txt35;
    private javax.swing.JComboBox<String> txt4;
    private javax.swing.JComboBox<String> txt5;
    private javax.swing.JComboBox<String> txt6;
    private javax.swing.JComboBox<String> txt7;
    private javax.swing.JComboBox<String> txt8;
    private javax.swing.JComboBox<String> txt9;
    private javax.swing.JButton validar;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
